### ISSUE TITLE
havhav cli

### ISSUE THREAD

**Issue by sadikkuzu** [tugrulcan/havhav#14]
Hi @tugrulcan 👋🏼 
What do you think if there is a CLI feature in this package?

```console
mocha@garden:~$ pip install havhav
mocha@garden:~$ havhav
A dog could detect a teaspoon of sugar if you added it to an Olympic-sized swimming pool full of water.
mocha@garden:~$ havhav 3
Dogs can see in color, though they most likely see colors similar to a color-blind human. They can see better when the light is low.
A dog can both sniff and breathe at the same time.
Dogs do not have an appendix.
```

**Comment by sadikkuzu** [comment]
![image](https://user-images.githubusercontent.com/23168063/193376678-7c5abd03-7b24-43eb-b12e-4c49a59b4c23.png)

**Comment by tugrulcan** [comment]
Hi @sadikkuzu 
Sorry for the late response, I'm on vacation these weeks. 

> What do you think if there is a CLI feature in this package?

Yes, why not! I was trying to find any use cases to check out [the Typer library](https://typer.tiangolo.com/)

**Comment by tugrulcan** [comment]
TYVM @sadikkuzu !
